remote_theme: LeNPaul/academic
url: "https://daniele-trappolini.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Daniele Trappolini" # the name of your site, e.g. ACME Corp.
description: "Phd Student in Data Science at Sapienza, University of Rome and INGV."

collections:
  projects:
    output: true
    permalink: /projects/:name/
