menu:
- {name: 'Projects', url: '/projects'}
- {name: 'Publications', url: '/publications'}
- {name: 'Courses', url: '/courses'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

social:
  - icon: 'github'
    link: 'https://github.com/Daniele-Trappolini'
  - icon: 'twitter'
    link: 'https://twitter.com/i/flow/login?redirect_after_login=%2FLeleTrappo'
  - icon: 'linkedin'
    link: 'https://www.linkedin.com/in/daniele-trappolini-5789761b6/'
  - icon: 'google'
    link: 'https://scholar.google.com/citations?user=lr_guzwAAAAJ&hl=it'

contacts:
  - name: 'Daniele Trappolini'
    title: 'Ph.D student'
    department: 'Department of Computer, Control and Management Engineering'
    institution: 'Sapienza University of Rome'
    address: 'Via Ariosto, 25, 00185 Roma RM'
    email: 'daniele.trappolini@uniroma1.com'
    image: 'assets/img/Sapienza_image.jpg'
    
  - title: 'INGV (Istituto Nazionale di Geofisica e Vulcanologia)'
    institution: 'Seismology Section'
    address: 'Via di Vigna Murata, 605, 00143 Roma RM'
    email: 'daniele.trappolini@ingv.it'
    image: 'assets/img/INGV_image.jpg'
