menu:
- {name: 'projects', url: '/projects'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

projects:
- {title: 'CDiffSD', name:'Cold Diffusion Model for Seismic Denoising', abstract: 'Seismic waves contain information about the earthquake (EQ) source and many forms of 
    noise deriving from the seismometer, anthropogenic effects, background noise associated with ocean waves, and microseismic noise. Separating the noise from the EQ 
    signal is a critical first step in EQ physics and seismic waveform analysis. However, this is difficult because optimal parameters for filtering noise typically 
    vary with time and may strongly alter the shape of the waveform. Recently, diffusion models have demonstrated encouraging outcomes when tackling challenging tasks 
    involving improving natural images and audio signals in conditioned and unconditioned restoration. In this study, we investigate the potential of utilizing an 
    advanced iterative diffusion model called "cold diffusion" to restore clean earthquake signals from noisy ones. Although the Cold Diffusion model proves to be a 
    highly promising work, it still requires further practical modifications, especially in real-world scenarios like ours. For this reason, our model proposes a 
    variant of the model developed by Yen et al.₁, where, in addition to the sampling implemented by Cold Diffusion, there is also an improved training algorithm to 
    enhance the model's ability to generalize better during the sampling process.', Details: 'ciao',image: 'assets/img/CDiffSD_poster.jpg', url: 'https://github.com/Daniele-Trappolini/Diffusion-Model-for-Earthquake'}
- {title: 'Ground Motion prediction', name:'Domain Adaptation on Ground Motion prediction', abstract: 'Domain Adaptation on Ground Motion prediction',Details: 'ciao',image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {title: 'Weather Nowcasting', name:'Mesoscale precipitation nowcasting from weather radar data using space-time-separable graph convolutional networks', abstract: 'Mesoscale precipitation nowcasting from weather radar data using space-time-separable graph convolutional networks',Details: 'ciao',image: 'assets/img/Weather_Nowcasting_Poster.jpg', url: 'primary-investigator'}


courses:
- {name: 'Foundamental of Data Science', url: 'https://github.com/stdrr/FDS-tutoring/tree/main'}

social:
- {icon: 'github', link: 'https://github.com/Daniele-Trappolini'}
- {icon: 'twitter', link: 'https://twitter.com/i/flow/login?redirect_after_login=%2FLeleTrappo'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/daniele-trappolini-5789761b6/'}

contacts:
- {name: 'Daniele Trappolini', title: 'Ph.D student', department: 'Department of Computer, Control and Management Engineering', institution: 'Sapienza University of Rome', email: 'daniele.trappolini@uniroma1.com', email2: 'daniele.trappolini@ingv.it', image: 'assets/img/contact.jpg'}
