menu:
- {name: 'projects', url: '/projects'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

projects:
- {title: 'CDiffSD', name:'Cold Diffusion Model for Seismic Denoising', abstract: 'Cold Diffusion Model for Seismic Denoising', Details: 'ciao',image: 'assets/img/CDiffSD_poster.jpg', url: 'https://github.com/Daniele-Trappolini/Diffusion-Model-for-Earthquake'}
- {title: 'Ground Motion prediction', name:'Domain Adaptation on Ground Motion prediction', abstract: 'Domain Adaptation on Ground Motion prediction',Details: 'ciao',image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {title: 'Weather Nowcasting', name:'Mesoscale precipitation nowcasting from weather radar data using space-time-separable graph convolutional networks', abstract: 'Mesoscale precipitation nowcasting from weather radar data using space-time-separable graph convolutional networks',Details: 'ciao',image: 'assets/img/Weather_Nowcasting_Poster.jpg', url: 'primary-investigator'}


courses:
- {name: 'Foundamental of Data Science', url: 'https://github.com/stdrr/FDS-tutoring/tree/main'}

social:
- {icon: 'github', link: 'https://github.com/Daniele-Trappolini'}
- {icon: 'twitter', link: 'https://twitter.com/i/flow/login?redirect_after_login=%2FLeleTrappo'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/daniele-trappolini-5789761b6/'}
- {icon: 'google scholar', link: 'https://scholar.google.com/citations?user=lr_guzwAAAAJ&hl=it'}
- {icon: 'google', link: 'https://www.pinlab.org/people'}

contacts:
- {name: 'Daniele Trappolini', title: 'Ph.D student', department: 'Department of Computer, Control and Management Engineering', institution: 'Sapienza University of Rome',address: 'Via Ariosto, 25, 00185 Roma RM',email: 'daniele.trappolini@uniroma1.com', image: 'assets/img/Sapienza_image.jpg'}
- {title: 'INGV (Istituto Nazionale di Geofisica e Vulcanologia)',institution: 'Seismology Section', address: 'Via di Vigna Murata, 605, 00143 Roma RM',email: 'daniele.trappolini@ingv.it', image: 'assets/img/INGV_image.jpg'}
