menu:
- {name: 'projects', url: '/projects'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

projects:
  - title: 'CDiffSD'
    name: 'CDiffSD'
    github: 'https://github.com/Daniele-Trappolini/Diffusion-Model-for-Earthquake' 
    details: 'Accepted at JGR: Machine Learning and Computation 6 May 2024 '
    image: 'assets/img/projects/JGR-CDIFFSD.jpg'
    
  - title: 'Encodec'
    name: 'SeismicAE: autoencoder for seismic waveforms embedding'
    github: 'soon available'
    details: 'Paper to be submitted'

  - title: 'Ground Motion prediction'
    name: 'Domain Adaptation on Ground Motion prediction'
    github: 'soon available'
    details: 'Work in progress'

  - title: 'Weather Nowcasting'
    name: 'Mesoscale precipitation nowcasting from weather radar data using space-time-separable graph convolutional networks'
    github: 'soon available'
    details: 'Paper to be submitted'


courses:
  - name: 'Foundamental of Data Science'
    url: 'FDS'

  - name: 'Elements of Seismology & Machine Learning'
    url: 'Seismology'
    slides: 'assets/slides/ML_seismology.pdf'

social:
  - icon: 'github'
    link: 'https://github.com/Daniele-Trappolini'
  - icon: 'twitter'
    link: 'https://twitter.com/i/flow/login?redirect_after_login=%2FLeleTrappo'
  - icon: 'linkedin'
    link: 'https://www.linkedin.com/in/daniele-trappolini-5789761b6/'
  - icon: 'google'
    link: 'https://scholar.google.com/citations?user=lr_guzwAAAAJ&hl=it'

contacts:
  - name: 'Daniele Trappolini'
    title: 'Ph.D student'
    department: 'Department of Computer, Control and Management Engineering'
    institution: 'Sapienza University of Rome'
    address: 'Via Ariosto, 25, 00185 Roma RM'
    email: 'daniele.trappolini@uniroma1.com'
    image: 'assets/img/Sapienza_image.jpg'
    
  - title: 'INGV (Istituto Nazionale di Geofisica e Vulcanologia)'
    institution: 'Seismology Section'
    address: 'Via di Vigna Murata, 605, 00143 Roma RM'
    email: 'daniele.trappolini@ingv.it'
    image: 'assets/img/INGV_image.jpg'
